baseURL = "https://carryree.github.io/tech-page/"
languageCode = "zh-cn"
title = "CarryRee's blog"
theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowToc = true
TocOpen = true

[params.profileMode]
enabled = true
title = "Documents"
subtitle = "Bruce Lee said,\"Empty your mind. Be formless, shapeless, like water. You put water into a cup, and it becomes the cup. You put water into a bottle, and it becomes the bottle. You put it into a teapot, and it becomes the teapot. Now water can flow or crash. Be water, my friend.\""
imageUrl = "avatar.jpg"
imageTitle = "avatar"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts/"

[[params.profileMode.buttons]]
name = "GitHub"
url = "https://github.com/CarryRee"
